# Generated by Django 2.1 on 2018-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180807_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
    ]
